org.gradle.jvmargs=-Xmx2G
org.gradle.configuration-cache=true

# Mod Global Properties
mod_version=1.2.0
maven_group=xyz.omegaware
archives_base_name=OmegaWare Addons

# 1.21.1 Fabric Properties
minecraft_version_1_21_1=1.21.1
yarn_mappings_1_21_1=1.21.1+build.3
loader_version_1_21_1=0.16.14

# 1.21.4 Fabric Properties
minecraft_version_1_21_4=1.21.4
yarn_mappings_1_21_4=1.21.4+build.8
loader_version_1_21_4=0.16.14

# 1.21.5 Fabric Properties
minecraft_version_1_21_5=1.21.5
yarn_mappings_1_21_5=1.21.5+build.1
loader_version_1_21_5=0.16.14

# 1.21.11 Fabric Properties
minecraft_version_1_21_11=1.21.11
yarn_mappings_1_21_11=1.21.11+build.6
loader_version_1_21_11=0.18.3
