name: Publish Release Draft
on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Set up Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: 21

            - name: Build with Gradle
              run: ./gradlew build -Pcommit=${{ github.sha }}

            - name: Get mod and Minecraft version
              id: get_versions
              run: |
                  mod_version=$(grep "^mod_version=" gradle.properties | cut -d'=' -f2)
                  echo "mod_version=$mod_version" >> $GITHUB_OUTPUT
                  echo "mc_version=1.21.11" >> $GITHUB_OUTPUT

            - name: Create GitHub Release Draft
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: v${{ steps.get_versions.outputs.mod_version }}
                  name: Release v${{ steps.get_versions.outputs.mod_version }} (MC ${{ steps.get_versions.outputs.mc_version }})
                  body: |
                    Release for mod version ${{ steps.get_versions.outputs.mod_version }} and Minecraft ${{ steps.get_versions.outputs.mc_version }}.
                  draft: true
                  prerelease: false
                  files: build/libs/*.jar
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
